# Generated by Django 2.1.3 on 2020-05-26 11:14

import api.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('audit_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('deleted', 'DELETED')], default='active', help_text='Active or InActive', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='On which date field is created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='On which date field is modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of Inventory', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(help_text='Inventory description', max_length=1440, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the Inventory', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))])),
                ('image', models.ImageField(help_text='Image Field for the Inventory', upload_to='media/', validators=[api.models.validate_image])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
